"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BadgeCheck, CheckCircle2, ChevronRight, Clock, MapPin, Package, Search, ShieldCheck, Sparkles, Store, Wrench } from "lucide-react";
import { CaseCard, EmptyState, SectionHeading } from "@/components/ui";
import { categories, experts } from "@/lib/demo-data";
import { useDemoStore } from "./demo-store";

export function ExpertsPage() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("전체");
  const [method, setMethod] = useState("전체");
  const filtered = useMemo(() => experts.filter((expert) => (category === "전체" || expert.categories.includes(category)) && (method === "전체" || expert.methods.includes(method)) && `${expert.name} ${expert.intro} ${expert.brands.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query, category, method]);

  return <div className="page-wrap experts-page"><div className="page-hero expert-hero"><div className="container"><span className="eyebrow">공개 답변 포트폴리오</span><h1>답변 이력으로 믿을 수 있는<br />전문가를 찾아보세요</h1><p>별점 하나보다 어떤 질문에 어떻게 답했고, 실제로 무엇을 해결했는지 먼저 보여드립니다.</p><div className="expert-principles"><span><BadgeCheck />인증 상태 확인</span><span><Sparkles />도움된 답변 집계</span><span><CheckCircle2 />실제 해결 결과</span></div></div></div><div className="container content-section"><div className="expert-filter"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="전문가, 브랜드, 수리 분야 검색" /></label><select value={category} onChange={(event) => setCategory(event.target.value)}><option>전체</option>{categories.map((item) => <option key={item.id}>{item.name}</option>)}</select><select value={method} onChange={(event) => setMethod(event.target.value)}><option>전체</option><option>택배</option><option>방문</option><option>출장</option></select></div><div className="expert-list-head"><strong>활동 중인 전문가</strong><span>{filtered.length}명</span></div><div className="expert-directory">{filtered.map((expert, index) => <article key={expert.id}><Link className="expert-directory-main" href={`/experts/${expert.id}`}><div className={`expert-photo photo-${(index % 3) + 1}`}>{expert.name[0]}{expert.activeNow && <i />}</div><div><div className="expert-name"><strong>{expert.name}</strong>{expert.status === "BUSINESS_VERIFIED" ? <span><BadgeCheck />사업자 인증</span> : <span className="personal-badge"><BadgeCheck />개인 전문가</span>}</div><p>{expert.intro}</p><div className="expert-tags">{expert.categories.map((tag) => <span key={tag}>{tag}</span>)}{expert.brands.slice(0, 3).map((tag) => <span key={tag}>{tag}</span>)}</div><div className="expert-logistics"><span><MapPin />{expert.regions.join(" · ")}</span><span><Package />{expert.methods.join(" · ")}</span><span><Clock />{expert.responseTime}</span></div></div><ChevronRight /></Link><div className="expert-directory-stats"><span><strong>{expert.answers}</strong>전체 답변</span><span><strong>{expert.helpfulAnswers}</strong>도움된 답변</span><span><strong>{expert.confirmedSolutions}</strong>해결 확인</span><span><strong>{expert.repairsCompleted}</strong>수리 완료</span></div></article>)}</div>{!filtered.length && <EmptyState icon={<Search />} title="조건에 맞는 전문가가 없어요" description="분야나 검색어를 바꿔 보세요." />}</div></div>;
}

export function ExpertProfilePage({ id }: { id: string }) {
  const expert = experts.find((entry) => entry.id === id) ?? experts[0];
  const { cases, comments } = useDemoStore();
  const answeredCaseIds = comments.filter((comment) => comment.expertId === expert.id).map((comment) => comment.caseId);
  const answered = cases.filter((item) => answeredCaseIds.includes(item.id));
  const fallbackCases = cases.filter((item) => expert.categories.includes(item.category)).slice(0, 3);
  return <div className="page-wrap expert-profile-page"><div className="expert-profile-cover"><div className="container"><div className="profile-identity"><div className="expert-profile-avatar">{expert.name[0]}{expert.activeNow && <i />}</div><div><div className="profile-name"><h1>{expert.name}</h1>{expert.status === "BUSINESS_VERIFIED" ? <span><BadgeCheck />사업자 인증 전문가</span> : <span className="personal-badge"><BadgeCheck />개인 전문가</span>}</div><p>{expert.intro}</p><div className="expert-logistics"><span><MapPin />{expert.regions.join(" · ")}</span><span><Package />{expert.methods.join(" · ")}</span><span><Clock />{expert.responseTime}</span></div></div></div><div className="profile-note"><ShieldCheck /><span><strong>수리 요청은 답변을 받은 글에서만 가능해요</strong><small>공개 답변을 통해 전문성을 확인한 뒤 질문자가 요청할 수 있습니다.</small></span></div></div></div><div className="container profile-layout"><main><section className="profile-section"><SectionHeading eyebrow="전문 분야" title="주로 이런 제품을 다뤄요" /><div className="skill-panels"><div><strong>카테고리</strong><p>{expert.categories.join(" · ")}</p></div><div><strong>취급 브랜드</strong><p>{expert.brands.join(" · ")}</p></div><div><strong>수리 가능 방식</strong><p>{expert.methods.join(" · ")}</p></div></div></section><section className="profile-section"><SectionHeading eyebrow="공개 답변" title="최근 답변한 질문" description="전문가의 설명 방식과 실제 활동을 확인해 보세요." /><div className="search-list">{(answered.length ? answered : fallbackCases).map((item) => <CaseCard key={item.id} item={item} compact />)}</div></section><section className="profile-section"><SectionHeading eyebrow="해결 사례" title="답변이 실제 해결로 이어진 사례" /><div className="case-grid">{cases.filter((item) => item.status === "RESOLVED" && expert.categories.includes(item.category)).slice(0, 2).map((item) => <CaseCard key={item.id} item={item} />)}</div></section></main><aside><div className="profile-stat-card"><span className="eyebrow">활동 기록</span><div><span><strong>{expert.answers}</strong>전체 답변</span><span><strong>{expert.validAnswers}</strong>유효 답변</span><span><strong>{expert.helpfulAnswers}</strong>도움된 답변</span><span><strong>{expert.confirmedSolutions}</strong>실제 해결 확인</span><span><strong>{expert.repairRequests}</strong>수리 요청</span><span><strong>{expert.repairsCompleted}</strong>수리 완료</span></div><small>최근 활동 · {expert.activeNow ? "오늘" : "3일 전"}</small></div><div className="profile-policy"><Store /><strong>광고보다 답변을 먼저 봐주세요</strong><p>수리온은 별점 하나가 아닌 공개 답변, 도움 수, 실제 해결 결과를 중심으로 전문가 활동을 보여줍니다.</p></div></aside></div></div>;
}
